/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import static codigo.Tokens.Int;
import static codigo.Tokens.Numero;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Reader;
import java.io.StringReader;
import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;
import java_cup.runtime.Symbol;
import javax.swing.JFileChooser;

/**
 *
 * @author Charly Ponce
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    private void analisarLexico() throws IOException{
        int cont =1;
        String expr = (String) txtResultado.getText();
        Lexer lexer = new Lexer(new StringReader(expr));
        String resultado = "LINEA" + cont + "\t\tSIMBOLO\n";
        while(true){
            Tokens token = lexer.yylex();
            if(token==null){
                txtResultado2.setText(resultado);
                return;
            }
            switch (token){
                case Linea:
                    cont++;
                    resultado += "LINEA" + cont + "\n";
                    break;
                case Int:
                    resultado += " <Reservada int>\t" + lexer.lexeme + "\n";
                    break;
                case If:
                    resultado += " <Reservada if>\t" + lexer.lexeme + "\n";
                    break;
                case Else:
                    resultado += " <else>\t" + lexer.lexeme + "\n";
                    break;
                case While:
                    resultado += " <while>\t" + lexer.lexeme + "\n";
                    break;
                case Igual:
                    resultado += " <igual>\t" + lexer.lexeme + "\n";
                    break;
                case Suma:
                    resultado += " <suma>\t" + lexer.lexeme + "\n";
                    break;
                case Resta:
                    resultado += " <resta>\t" + lexer.lexeme + "\n";
                    break;
                case Multiplicacion:
                    resultado += " <multiplicacion>\t" + lexer.lexeme + "\n";
                    break;
                case Division:
                    resultado += " <division>\t" + lexer.lexeme + "\n";
                    break;
                case Parentesis_a:
                    resultado += " <paraentesis_a>\t" + lexer.lexeme + "\n";
                    break;
                case Parentesis_c:
                    resultado += " <parentesis_c>\t" + lexer.lexeme + "\n";
                    break;
                case Llave_a:
                    resultado += " <llave_a>\t" + lexer.lexeme + "\n";
                    break;
                case Llave_c:
                    resultado += " <llave_c>\t" + lexer.lexeme + "\n";
                    break;
                case Main:
                    resultado += " <main>\t" + lexer.lexeme + "\n";
                    break;
                case P_coma:
                    resultado += " <p_coma>\t" + lexer.lexeme + "\n";
                    break;
                case Identificador:
                    resultado += " <identificador>\t" + lexer.lexeme + "\n";
                    break;
                case Numero:
                    resultado += " <numero>\t" + lexer.lexeme + "\n";
                    break;
                case ERROR:
                    resultado += " <Simobolo no definido>\n" + lexer.lexeme + "\n";
                    break;
                default:
                    resultado += "<" + lexer.lexeme + " >\n";
                    break;
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        btnArchivo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResultado2 = new javax.swing.JTextArea();
        btnAnalizarlex = new javax.swing.JButton();
        btnLimpiarlex = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAnalizarsin = new javax.swing.JButton();
        btnLimpiarsin = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtResultado3 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        btnArchivo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codigo/Imagenes/adjunto-archivo.png"))); // NOI18N
        btnArchivo.setText("AbrirArchivo");
        btnArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivoActionPerformed(evt);
            }
        });

        txtResultado2.setColumns(20);
        txtResultado2.setRows(5);
        jScrollPane2.setViewportView(txtResultado2);

        btnAnalizarlex.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnAnalizarlex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codigo/Imagenes/buscar.png"))); // NOI18N
        btnAnalizarlex.setText("Analizar");
        btnAnalizarlex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarlexActionPerformed(evt);
            }
        });

        btnLimpiarlex.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnLimpiarlex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codigo/Imagenes/limpieza-de-datos.png"))); // NOI18N
        btnLimpiarlex.setText("Limpiar");
        btnLimpiarlex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarlexActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Analizador Lexico");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Analizador Sintatico");

        btnAnalizarsin.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnAnalizarsin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codigo/Imagenes/buscar.png"))); // NOI18N
        btnAnalizarsin.setText("Analizar");
        btnAnalizarsin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarsinActionPerformed(evt);
            }
        });

        btnLimpiarsin.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnLimpiarsin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codigo/Imagenes/limpieza-de-datos.png"))); // NOI18N
        btnLimpiarsin.setText("Limpiar");

        txtResultado3.setColumns(20);
        txtResultado3.setRows(5);
        jScrollPane3.setViewportView(txtResultado3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(btnArchivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAnalizarlex, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpiarlex, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAnalizarsin)
                .addGap(61, 61, 61)
                .addComponent(jLabel2)
                .addGap(94, 94, 94)
                .addComponent(btnLimpiarsin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(jLabel1)
                .addContainerGap(322, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimpiarlex, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAnalizarlex, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(75, 75, 75)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimpiarsin, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAnalizarsin, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivoActionPerformed
        
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File archivo = new File(chooser.getSelectedFile().getAbsolutePath());
        try {
            String ST = new String(Files.readAllBytes(archivo.toPath()));
            txtResultado.setText(ST);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnArchivoActionPerformed

    private void btnAnalizarlexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarlexActionPerformed
        try {
            analisarLexico();
        } catch (IOException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAnalizarlexActionPerformed

    private void btnLimpiarlexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarlexActionPerformed
        
    }//GEN-LAST:event_btnLimpiarlexActionPerformed

    private void btnAnalizarsinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarsinActionPerformed
        String ST = txtResultado.getText();
        Sintax s = new Sintax(new codigo.LexerCup(new StringReader(ST)));
        
        try {
            s.parse();
            txtResultado3.setText("Analisis realizado correctamente");
            txtResultado3.setForeground(new Color(25, 111, 61));
        } catch (Exception ex) {
            Symbol sym = s.getS();
            txtResultado3.setText("Error de sintaxis. Linea: " + (sym.right + 1) + " COlumna: "+ (sym.left +1) + ", Texto: \"" + sym.value + "\"");
            txtResultado3.setForeground(Color.red);
        }
    }//GEN-LAST:event_btnAnalizarsinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalizarlex;
    private javax.swing.JButton btnAnalizarsin;
    private javax.swing.JButton btnArchivo;
    private javax.swing.JButton btnLimpiarlex;
    private javax.swing.JButton btnLimpiarsin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtResultado;
    private javax.swing.JTextArea txtResultado2;
    private javax.swing.JTextArea txtResultado3;
    // End of variables declaration//GEN-END:variables
}
